# Generated by Django 4.0.1 on 2022-01-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
